default:
  navigation:
    - title: Ropa
      subtitle: Categorías
      url: /t/ropa
      items:
        - :title: Tops
          :url: /t/ropa/tops
        - :title: Sweters
          :url: /t/ropa/sweters
        - :title: Camisetas
          :url: /t/ropa/camisetas
        - :title: Trajes de Baño
          :url: /t/ropa/trajes-de-baño
        - :title: Faldas
          :url: /t/ropa/faldas
        - :title: Shorts
          :url: /t/ropa/shorts
        - :title: Jeans
          :url: /t/ropa/jeans
        - :title: Pantalones
          :url: /t/ropa/pantalones
      promo_banners:
#        - subtitle: New collection
#          title: Summer 2019
#          url: /t/new-collection/summer-2019
#          image: 'meganav/promo_banner_left-first-category.jpg'
#        - subtitle: Special Offers
#          title: Get up to 30% off
#          url: /t/special-offers/30-off
#          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Accesorios
      subtitle: Comming Soon
#      url: /t/accesories
      items:
#        - :title: Accesorios
#          :url: /t/men/shirts
#        - :title: T-shirts
#          :url: /t/men/t-shirts
#        - :title: Sweaters
#          :url: /t/men/sweaters
#        - :title: Jackets and Coats
#          :url: /t/men/jackets-and-coats
      promo_banners:
#        - subtitle: New collection
#          title: Summer 2019
#          url: /t/new-collection/summer-2019
#          image: 'meganav/promo_banner_left-second-category.jpg'
#        - subtitle: Special Offers
#          title: Get up to 30% off
#          url: /t/special-offers/30-off
#          image: 'meganav/promo_banner_right-second-category.jpg'

    - title: Sale
#      subtitle: Categories
#      url: /t/accesories
      items:
#        - :title: Sale
#          :url: /t/men/shirts
#        - :title: T-shirts
#          :url: /t/men/t-shirts
#        - :title: Sweaters
#          :url: /t/men/sweaters
#        - :title: Jackets and Coats
#          :url: /t/men/jackets-and-coats
      promo_banners:
#        - subtitle: New collection
#          title: Summer 2019
#          url: /t/new-collection/summer-2019
#          image: 'meganav/promo_banner_left-second-category.jpg'
#        - subtitle: Special Offers
#          title: Get up to 30% off
#          url: /t/special-offers/30-off
    #          image: 'meganav/promo_banner_right-second-category.jpg'